### PR TITLE
added usd+ on optimism and arbitrum chains

### PR DESCRIPTION
**Pull request by rrr-source**

### CODE REVIEW

**Comment by rrr-source** [comment]
the links and info is inside the pull_request_template.md

**Review by philippe-git — CHANGES_REQUESTED** [review]
Please undo the changes you made to the pull_request_template.md file, this shouldn't be touched; thanks for providing those links though, next time feel free to simply paste them in the PR description!

**Comment by rrr-source** [comment]
Make sure file is PNG 200x200 pixels with the file name LOWER CASED

Team you are making the PR for:
Team: Overnight Finance 
Link: https://overnight.fi/
Link where we may find the added token on an official website/twitter to verify it's official:
https://www.coingecko.com/en/coins/overnight-fi-usdplus
https://coinmarketcap.com/currencies/usd/
https://defillama.com/protocol/overnight-usd+
https://twitter.com/overnight_fi

**Comment by rrr-source** [comment]
Hi! Could you please explain why the merging is blocked?
In the previous commit, you asked to undo the changes in the pull_request_template.md. 
-Please undo the changes you made to the pull_request_template.md file, this shouldn't be touched; thanks for providing those links though, next time feel free to simply paste them in the PR description!

Then I undid the changes in the pull_request_template.md. file, and pushed it. 

cyurve

As you can see i have added the icons in the previous commit already, I can't push them twice.
curve

**Review by philippe-git — APPROVED** [review]

**Comment by philippe-git** [comment]
Merged, thanks for the changes! I didn't get the first notification of your changes, hence the wait, thanks for your patience

**Pull request merged**
