### PR TITLE
Create 0x1f1c8b8caa6d207c68f1bbf26b8f38ac83fab086.png

### PR DESCRIPTION
**Pull request by denisimo5335**
UNIV

### CODE REVIEW

**Comment by philippe-git** [comment]
Please don't post images as comments on your pull requests, they must be inside the appropriate folder, and then committed. Same problem here as in #390, I invited you to create another PR when you've fixed this

image

**Comment by denisimo5335** [comment]
Ok sounds good, where I upload the images in which folder ? Directly at GitHub browser or use a code  editor ?

**Comment by philippe-git** [comment]
Whichever way you prefer! It's very easy directly on GitHub, you can go to the `images/assets` on your forked repository, and then open a PR. You've already done with the PR here, the only thing you need to do differently is to add the correct image file inside the folder

**Comment by denisimo5335** [comment]
Sorry to bother sir, 
Ive created a forked repo and now how do I add the icon? I’ve tried all the options?

Thanks, very appreciated

**Comment by denisimo5335** [comment]
Its says uploads disabled

**Comment by philippe-git** [comment]
It seems you've been able to do this in #396 , let's continue the conversation there

**Pull request closed without merging**
