### PR TITLE
CrossCurve xWETH pool

### PR DESCRIPTION
**Pull request by stas-fi**

### CODE REVIEW

**Comment by philippe-git** [comment]
Is there an issue with the fantom icon?

**Comment by stas-fi** [comment]
> Is there an issue with the fantom icon?

what do you mean?

**Comment by philippe-git** [comment]
It doesn't look like all the others:

image

**Comment by stas-fi** [comment]
the icon is correct, it follows the style of the other "x" pool icons (xStable for example: https://github.com/curvefi/curve-assets/pull/451/files#diff-61e74faf3fc2cfb8d0dab50fec38e94f8f1a954c1cf8cb9ba64d88e91753c176)

**Comment by philippe-git** [comment]
Ahh sounds good, it looked like human error to my untrained eye, thanks for clarifying!

**Pull request merged**
