### PR TITLE
Add QUINTA Token files via upload

### PR DESCRIPTION
**Pull request by geopayme**

### CODE REVIEW

**Review by philippe-git — CHANGES_REQUESTED** [review]
Hi, can you please remove the uppercase version of 0x3D5a15A9d8EA1D76A32cD70eea882968992d8D95, and make 0x691c25c461dafc47792b6e4d674fbb637bca1c6f 200x200?

**Comment by geopayme** [comment]
Ok will correct I tried but could not see where the deletion option was?

**Comment by philippe-git** [comment]
Thanks!

**Comment by geopayme** [comment]
Awesome, thanks for the update! Do you know how long it takes for the
images to cycle ?

*"I don't need to know everything; I just need to know where to find it." *
*A. Einstein.*

If you need to reach your people fast, there's no better way than with
"mobile." Mobile is direct, accurate, and personal.

This email may contain confidential and privileged information. If you are
not the intended recipient (or have received this email by mistake), please
notify the sender immediately and destroy this email. Any unauthorized
copying, disclosure, or distribution of the material in this email is
strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. So, the sender does not accept liability
for any errors or omissions in this message that may arise because of email
transmission.

**Pull request merged**
