### PR TITLE
0x1f1c8b8caa6d207C68f1bbf26b8f38ac83fab086.png

### PR DESCRIPTION
**Pull request by denisimo5335**
logo
add integrations logos

### CODE REVIEW

**Review by philippe-git — CHANGES_REQUESTED** [review]
The image seems invalid

**Comment by philippe-git** [comment]
There wasn't any updated commit, the file hasn't changed

**Comment by philippe-git** [comment]
The image you committed is still empty 🤷‍♀️

image

**Comment by denisimo5335** [comment]
Hello 👋 
We are trying to integrate our dapp platform with your platform and add your token as option in the list, as well as other options as borrowing in the future. I made one PR pls check at platform integration, also I added the logo in the platform images
Looking forward to more collaborations

**Comment by philippe-git** [comment]
See conversation in https://github.com/curvefi/curve-external-integrations/pull/44

**Pull request closed without merging**
