### PR TITLE
add axlUSDC across chains

### PR DESCRIPTION
**Pull request by aditya-manit**

### CODE REVIEW

**Comment by philippe-git** [comment]
Hey, this PR is perfect, yet I have one ask before merging it: to avoid confusion, since axlUSDC on all those chains is a wrapper, could you make the icon at least slightly different from the standard USDC icon? perhaps with the axelar logo in the bottom right corner or something?

**Comment by aditya-manit** [comment]
Okay Sure, will update it today

**Comment by aditya-manit** [comment]
Updated

**Review by philippe-git — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
