### PR TITLE
univ token icon

### PR DESCRIPTION
**Pull request by denisimo5335**

### CODE REVIEW

**Review by philippe-git — CHANGES_REQUESTED** [review]
There still seems to be an issue with your image:

image

An online converter also had issues opening it, so I'm not sure what's wrong with it, but you should try and opening it / saving it with another software until GitHub is able to display it properly

**Comment by denisimo5335** [comment]
Hello again
So when you got the folder curve-assets/images/assets than when I have to Create new file? Commit and than upload the picture? Because doesn’t letting me to upload file, shows this uploads are disabled
Plese guide me trying to create a pool

**Comment by denisimo5335** [comment]
I think I got it right this time
Can you check.
Thanks for your time

**Comment by philippe-git** [comment]
You did not, it wasn't in the right folder. But at least this time I had a valid image to work with, so I've moved it to the right folder and merged it (here https://github.com/curvefi/curve-assets/pull/402), the icon is now live! Sorry it's convoluted if you're not used to git, don't hesitate to have someone else give you a hand next time you want to submit an icon

**Pull request closed without merging**
